# -*- coding: utf-8 -*-
#!/usr/bin/env python

IS_CONSOLE_PRINT=True
ZOOKEEPER_HOST = "127.0.0.1"
ZOOKEEPER_PORT = "2181"
MONITOR_PARENT_PATH = "/test"
MONITOR_LEADER_INTEVAL = 60

ACTIVEMQ_HOST='127.0.0.1'
ACTIVEMQ_PORT=61613
ACTIVEMQ_USER=''
ACTIVEMQ_PASSWORD=''

RPYC_LEADER_HOST='127.0.0.1'
RPYC_LEADER_PORT=18511
RPYC_SECRET_KEY = "ctmj#&amp;8hrgow_^sj$ejt@9fzsmh_o)-=(byt5jmg=e3#foya6u"

RPYC_WORK_HOST=''
RPYC_WORK_PORT=''

AUTO_PLATFORM = "local"